name: wrapped

services:
  frontend:
    container_name: wrapped_frontend
    image: wrapped.azurecr.io/wrapped/frontend
    ports:
      - "80:3000" # HOST:CONTAINER
    depends_on:
      - backend

  backend:
    container_name: wrapped_backend
    image: wrapped.azurecr.io/wrapped/backend
    depends_on:
      - database

  database:
    container_name: wrapped_database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
