name: wrapped

services:
  nginx:
    image: nginx:latest
    container_name: wrapped_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    image: wrapped.azurecr.io/frontend
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    tty: true
    depends_on:
      - backend

  backend:
    image: wrapped.azurecr.io/backend
    depends_on:
      - database

  database:
    container_name: wrapped_database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
