name: wrapped

services:
  frontend:
    container_name: wrapped_frontend
    build: ./frontend
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
    tty: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    container_name: wrapped_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - database
  database:
    container_name: wrapped_database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
