name: wrapped

services:
    nginx:
        container_name: wrapped_nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - frontend
            - backend

    frontend:
        container_name: wrapped_frontend
        build: ./frontend
        env_file:
            - ./backend/.env.development
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        container_name: wrapped_backend
        build: ./backend
        env_file:
            - ./backend/.env.development
        environment:
            - PRODUCTION=False
        ports:
            - "8000:8000"
        depends_on:
            - database

    database:
        container_name: wrapped_database
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
