name: wrapped_production_builder

services:
    frontend:
        image: asheshadri2005/wrapped:frontend
        container_name: wrapped_frontend_production_builder
        build:
            context: ../frontend
            dockerfile: ../frontend/production.Dockerfile
        env_file:
            - ../frontend/.env.production
        ports:
            - "80:3000"
        depends_on:
            - backend

    backend:
        image: asheshadri2005/wrapped:backend
        container_name: wrapped_backend_production_builder
        build:
            context: ../backend
            dockerfile: ../backend/production.Dockerfile
        env_file:
            - ../backend/.env.production
        ports:
            - "8000:8000"
        depends_on:
            - database

    database:
        container_name: wrapped_database_production_builder
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data_production_builder:/var/lib/postgresql/data

volumes:
    postgres_data_production_builder:
