name: wrapped_production

services:
    nginx:
        image: asheshadri2005/wrapped:nginx
        container_name: wrapped_nginx_production_builder
        build:
            context: ../nginx
            dockerfile: ../nginx/production.Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - frontend1
            - frontend2
            - frontend3
            - backend

    frontend1:
        container_name: wrapped_frontend_production1
        image: asheshadri2005/wrapped:frontend
        restart: always
        environment:
            - NEXT_PUBLIC_BASE_URL=https://cs2340-group-39.com
            - SESSION_PASSWORD=MeQkSmT12smYgpHp8i9CNTscvF5RJItEsY0WlAvlJuw=
            - SPOTIFY_CLIENT_ID=1e6a1b8a508540eca571d631877f8842
            - SPOTIFY_CLIENT_SECRET=6158b7b2c393486e9d3415abef3f735c
        depends_on:
            - backend

    frontend2:
        container_name: wrapped_frontend_production2
        image: asheshadri2005/wrapped:frontend
        restart: always
        environment:
            - NEXT_PUBLIC_BASE_URL=https://cs2340-group-39.com
            - SESSION_PASSWORD=MeQkSmT12smYgpHp8i9CNTscvF5RJItEsY0WlAvlJuw=
            - SPOTIFY_CLIENT_ID=1e6a1b8a508540eca571d631877f8842
            - SPOTIFY_CLIENT_SECRET=6158b7b2c393486e9d3415abef3f735c
        depends_on:
            - backend

    frontend3:
        container_name: wrapped_frontend_production3
        image: asheshadri2005/wrapped:frontend
        restart: always
        environment:
            - NEXT_PUBLIC_BASE_URL=https://cs2340-group-39.com
            - SESSION_PASSWORD=MeQkSmT12smYgpHp8i9CNTscvF5RJItEsY0WlAvlJuw=
            - SPOTIFY_CLIENT_ID=1e6a1b8a508540eca571d631877f8842
            - SPOTIFY_CLIENT_SECRET=6158b7b2c393486e9d3415abef3f735c
        depends_on:
            - backend

    backend:
        container_name: wrapped_backend_production
        image: asheshadri2005/wrapped:backend
        restart: always
        environment:
            - SECRET_KEY="django-insecure-71egvc!bqkur)ftmxfexk+na*^*+u5c&k6g7=dbq)yvdy9_)ct"
            - DEBUG=False
            - BASE_URL=https://cs2340-group-39.com
            - RESEND_API_KEY=re_V3nm8deF_H3xhXc3V2svY8DkwgVmcM9kt
            - RESEND_FROM_EMAIL=noreply@cs2340-group-39.com
            - SPOTIFY_CLIENT_ID=1e6a1b8a508540eca571d631877f8842
            - SPOTIFY_CLIENT_SECRET=6158b7b2c393486e9d3415abef3f735c
        depends_on:
            - database

    database:
        container_name: wrapped_database_production
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data_production:/var/lib/postgresql/data

volumes:
    postgres_data_production:
