services:
  frontend:
    container_name: wrapped_frontend
    image: asheshadri2005/wrapped:frontend
    restart: always
    environment:
      - SUPABASE_URL=
      - SUPABASE_SERVICE_ROLE_KEY=
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: wrapped_backend
    image: asheshadri2005/wrapped:backend
    restart: always
    environment:
      - SECRET_KEY=django-insecure-71egvc!bqkur)ftmxfexk+na*^*+u5c&k6g7=dbq)yvdy9_)ct
      - SUPABASE_DB_HOST=aws-0-us-east-1.pooler.supabase.com
      - SUPABASE_DB_NAME=postgres
      - SUPABASE_DB_PORT=6543
      - SUPABASE_DB_USER=postgres.ghabyrvbdvupowhfzopm
      - SUPABASE_DB_PASSWORD=B70qVPQD8ORBmO7Q
      - SUPABASE_URL=
      - SUPABASE_SERVICE_ROLE_KEY=
