# Generated by Django 5.1 on 2024-12-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wrapped",
            old_name="albums",
            new_name="tracks",
        ),
    ]
