# Generated by Django 5.1 on 2024-12-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0002_rename_albums_wrapped_tracks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wrapped",
            name="genres",
        ),
        migrations.AddField(
            model_name="wrapped",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
