# Generated by Django 5.1 on 2024-11-29 02:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [("users", "0001_initial")]

  operations = [
    migrations.CreateModel(
      name="BlacklistedToken",
      fields=[
        (
          "id",
          models.BigAutoField(
            auto_created=True,
            primary_key=True,
            serialize=False,
            verbose_name="ID",
          ),
        )
      ],
    ),
    migrations.AddField(
      model_name="user",
      name="email_verification_code",
      field=models.UUIDField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name="user",
      name="email_verification_code_created_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name="user",
      name="email_verified_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name="user",
      name="token_salt",
      field=models.UUIDField(default=uuid.uuid4),
    ),
    migrations.AlterField(
      model_name="user",
      name="uuid",
      field=models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        primary_key=True,
        serialize=False,
        unique=True,
      ),
    ),
  ]
