# Generated by Django 5.1.3 on 2024-11-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_supabaseuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supabaseuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
