# Generated by Django 5.1.3 on 2024-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_supabaseuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supabaseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
