# Generated by Django 5.1 on 2024-11-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="spotify_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
