# Generated by Django 5.1 on 2024-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_profile_spotify_access_token_expires_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="spotify_access_token_expires_in",
        ),
        migrations.AddField(
            model_name="profile",
            name="spotify_access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
