name: CI Pipeline

on:
    push:
        branches: [ "main", "actions-tests" ]
    pull_request:
        branches: [ "main", "actions-tests" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip #optional, speeds up workflow
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/backend/requirements.txt') }}

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Run migrations
        working-directory: ./backend
        run: |
          python manage.py migrate

      - name: Run backend tests with coverage
        working-directory: ./backend
        env:
          DJANGO_SETTINGS_MODULE: core.settings
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml --cov-fail-under=80

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: ./backend/coverage.xml

    #we aren't using codecov, an online tool
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       files: ./backend/coverage.xml
    #       flags: backend

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/frontend/package-lock.json') }}

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Run frontend tests with coverage
        working-directory: ./frontend
        run: |
          npm run test:ci

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: ./frontend/coverage

    #we aren't using codecov, an online tool
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v4
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #       directory: ./frontend/coverage
    #       flags: frontend
