# Lints across all languages, can find individual linters used in its github
# https://github.com/github/super-linter
name: Lint Code Base

on:
  push:
    branches: [ "main", "actions-tests" ]
  pull_request:
    branches: [ "main", "actions-tests" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false  # Set to true if want to validate files not newly added as well
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
